### ISSUE TITLE
 Data dir doesnt exist, creating...: /sessions/_IGNORE_session

### ISSUE THREAD

**Issue by hasanbasri1993** [open-wa/wa-automate-docker#61]
here my docker-compose.yaml
```
version: "3.9"
services:

  browser:
    image: browserless/chrome:latest
    hostname: browser
    init: true
    volumes:
      - "/home/ubuntu/dulido-open-wa/sessions:/sessions"
    ports:
      - "3000:3000"
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    environment:
      CONNECTION_TIMEOUT: -1
      KEEP_ALIVE: 'true'
      WORKSPACE_EXPIRE_DAYS: 1
      ENABLE_CORS: 'true'
      CHROME_REFRESH_TIME: 86400000
      DEFAULT_BLOCK_ADS: 'true'
      FUNCTION_ENABLE_INCOGNITO_MODE: 'true'
      ENABLE_XVBF: 'true'
      CHROME_PATH: '/usr/bin/google-chrome'
      USE_CHROME_STABLE: 'true'
      NODE_ENV: 'production'

  owa:
    image: openwa/wa-automate:latest
    hostname: owa
    init: false
    restart: on-failure
    volumes:
      - "/home/ubuntu/dulido-open-wa/sessions:/sessions"
    depends_on:
      - browser
    ports:
      - "8002:8002"
    environment:
      WA_BROWSER_WS_ENDPOINT: 'ws://browser:3000'
      WA_DISABLE_SPINS: 'true'
      # Uncomment next line and add the session data base64 string to authenticate the session without the need to scan it again
      # WA_SESSION_DATA: ''

volumes:
  sessions:
```

```
You can also authenticate the session at: http://localhost:8002
- Starting
- Version: 4.55.2
- Initializing WA
- Using custom chromium args with multi device will cause issues! Please remove them: 
- Launching Browser
- MD Enabled, turning off incognito mode.
- Data dir: /sessions/_IGNORE_session
- Data dir doesnt exist, creating...: /sessions/_IGNORE_session
Error: EACCES: permission denied, mkdir '/sessions/_IGNORE_session'
```

Thanks u
